route:
  receiver: 'wechat'

receivers:
  - name: 'wechat'
    wechat_configs:
      - send_resolved: true
        #api_secret: <api_secret>#
        #corp_id: <corp_id>#
        #agent_id: <agent_id>#
        #to_party: <to_party>#
